name: Feature request
description: Suggest an idea for this project
title: "[ENHANCEMENT]: "
labels: [enhancement, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting a bug report to help us improve.

        If you have a support question about how to use the module, no one is monitoring the issues to answer those. Consider posting on StackOverflow instead using the "passport-saml" tag or using [GitHub Discussions](https://github.com/node-saml/passport-saml/discussions).

        ## Spec-driven development

        This project is focused on compliance with the SAML 2.0 specification. For any bug report that
        involves the SAML spec, please link to the related parts of the spec and quote the passages too.

        Start here: http://saml.xml.org/saml-specifications

        You might also check the spec to confirm that it doesn't address your particular bug and mention
        that you found no references in the spec concerning your issue.

        ## Community development model

        `passport-saml` is maintained by a number of current users. There is no author or primary maintainer
        waiting to add features for you. We encourage this space to discuss the best way to add a feature, but we depend on users like you to add the feature. All new features should come with tests and appropriate documentation updates.
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe...
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe teh solution you'd like...
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe the alternatives you've considered...
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
